<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class EventsImage extends Model
{


    protected  $table = "events_image";

    protected $fillable = [
        "users_event_id",
        "slug",
        "image",


    ];

    public function getRouteKeyName()
    {
        return "slug"; // TODO: Change the autogenerated stub
    }

    public function usersEvent()
    {
        return $this->belongsTo('App\UsersEvent','users_event_id');
    }
}
