<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class JobSkills extends Model
{
    use SoftDeletes;

    protected  $table = "job_skills";
    protected  $fillable = [
        "users_job_id",
        "slug",
        "skills",
    ];
    public function getRouteKeyName()
    {
        return "slug"; // TODO: Change the autogenerated stub
    }
}
