<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UsersProfessionalDetail extends Model
{
    use SoftDeletes;
    protected  $table = "users_professional_detail";

    protected $fillable = [
        'user_id',
        'slug',
        'role',
        'company_firm_or_college_university',
        'start_date',
        'end_date_of_working_currently',
        'salary_stripend',




    ];

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function usersCompany(){
        return $this->belongsTo(User::class,'company_firm_or_college_university_id','id')->where('user_type','work_architecture_firm_companies');
    }
    public function usersCollege(){
        return $this->belongsTo(User::class,'company_firm_or_college_university_id','id')->where('user_type','work_architecture_college');
    }
    
}
